services:
  grpcexample:
    build: 
      context: .
      args:
        - BUILD_MODE=${BUILD_MODE}
        - GITHUB_TOKEN=123
    pull_policy: always
    restart: on-failure
    container_name: grpcexample
    secrets:
       - grpcexample_config.yaml
    ports:
      - 4004:4004

secrets:
  grpcexample_config.yaml:
    file: ../.secrets/grpcexample_config.yaml
